### ISSUE TITLE
Triple quoted docstrings are incorrectly indented with cblack 22.3.0

### ISSUE THREAD

**Issue by natemccurdy** [pausan/cblack#17]
This looks like the same problem kind of problem as #2 where this:
```python
class Foo:
  """
  Hello this is a long sentance. Hello this is a long sentance. Hello this is a long sentance.
  Hello this is a long sentance. Hello this is a long sentance. Hello this is a long sentance.
  """

  def something():
    """
    This is another docstring.
    """
```

Gets turned into this after running cblack version `22.3.0` against it:
```python
class Foo:
  """
    Hello this is a long sentance. Hello this is a long sentance. Hello this is a long sentance.
    Hello this is a long sentance. Hello this is a long sentance. Hello this is a long sentance.
    """

  def something():
    """
        This is another docstring.
        """
```

This does not happen on version `21.6b0` of cblack.

**Comment by pausan** [comment]
Thanks for reporting this issue. Long story short, I've fixed the underlying issue and updated cblack to 22.6.0 to match black 22.6.0 so you can run:
`pip3 install cblack --upgrade`

Version 22.3.0 will remain broken if cblack is installed locally (whereas it will likely work if installed system-wide). Anyway, in version 22.6.0 it should work both ways, hopefully :crossed_fingers:

I'm closing this issue since it should be resolved, but feel free to reopen if it has not been fixed on your end.
